#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

caddy_version="2.11.4"
caddy_hash="8220d1f013b6f27510247b2360c9e0ca9f018feebd82515f07635318b34ff9777ccc8fd0b6e6f2486ce3a33fe389fbb7db12d05baa474f4587509fb4f5ebf1c9"
if [ "$TARGETARCH" == "arm64" ]; then
  caddy_hash="d5a7c423853c24a799765e0e8210d5c7c22a8f56ed37a3cae2fb9f58be138853c02b4efd6b59d576e6d8c7c0d30b9c1592deeaa6a536ff69bcca23b8c1ea709c"
fi

task_working_dir
download "https://github.com/caddyserver/caddy/releases/download/v${caddy_version}/caddy_${caddy_version}_linux_${TARGETARCH}.tar.gz" "sha512" "$caddy_hash"
extract_download "caddy_${caddy_version}_linux_${TARGETARCH}.tar.gz"

install -D -m 755 "caddy" "$TEST_INSTALL_PREFIX/bin/caddy"

stamp
