#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

glauth_version="2.5.2"
glauth_hash="35ac70080bf6648cfeda3f0af47094db7e012a664f0eb0b57868205cd843e23f"
if [ "$TARGETARCH" == "arm64" ]; then
  glauth_hash="64ff0e26ea8fc41e62790976c4e8efdc3d3a5ba3155f06bbeb4beb8ab59505f6"
fi

task_working_dir
download "https://github.com/glauth/glauth/releases/download/GLAuth-v$glauth_version/glauth-linux-${TARGETARCH}" "sha256" "$glauth_hash"

install -D -m 755 "_persist/downloads/glauth-linux-${TARGETARCH}" "$TEST_INSTALL_PREFIX/bin/glauth"

stamp
