#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

mailpit_version="1.30.6"
mailpit_hash="00f7570bf47c9683944f6189379ce4b7d4974b1c9cd911f93c55d4ad945bf3d2"
if [ "$TARGETARCH" == "arm64" ]; then
  mailpit_hash="80ecee9cd8d28c4eb908dc27c5ce4505a708b4d5ad4602eac0c6540a8df53f53"
fi

task_working_dir
download "https://github.com/axllent/mailpit/releases/download/v${mailpit_version}/mailpit-linux-${TARGETARCH}.tar.gz" "sha256" "$mailpit_hash"
extract_download "mailpit-linux-${TARGETARCH}.tar.gz"

install -D -m 755 "mailpit" "$TEST_INSTALL_PREFIX/bin/mailpit"

stamp
