#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

mailpit_version="1.31.0"
mailpit_hash="076b5ded9a2182842b93e761b9586a1a251445bffe2666f9f22a6dc14470237d"
if [ "$TARGETARCH" == "arm64" ]; then
  mailpit_hash="db3e685ed59d58354a29a4e7bfd0497f050af771a41e122aabdb0bd4fb915952"
fi

task_working_dir
download "https://github.com/axllent/mailpit/releases/download/v${mailpit_version}/mailpit-linux-${TARGETARCH}.tar.gz" "sha256" "$mailpit_hash"
extract_download "mailpit-linux-${TARGETARCH}.tar.gz"

install -D -m 755 "mailpit" "$TEST_INSTALL_PREFIX/bin/mailpit"

stamp
