#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

mailpit_version="1.30.5"
mailpit_hash="b1499b23e6207d2728a0f154fd27370d0f608dd8ae1a63b734d089dc7f7a8d6f"
if [ "$TARGETARCH" == "arm64" ]; then
  mailpit_hash="c4c0a587770af1d5fb192e7b580aebfc03115c93da2af308a4b2e227c7d06cd2"
fi

task_working_dir
download "https://github.com/axllent/mailpit/releases/download/v${mailpit_version}/mailpit-linux-${TARGETARCH}.tar.gz" "sha256" "$mailpit_hash"
extract_download "mailpit-linux-${TARGETARCH}.tar.gz"

install -D -m 755 "mailpit" "$TEST_INSTALL_PREFIX/bin/mailpit"

stamp
