#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

hugo_version="0.164.0"
hugo_hash="fea17b8c076f950bb2e9f9486667bdaa29422883888d509d63931c73e8a9b3a4"
if [ "$TARGETARCH" == "arm64" ]; then
  hugo_hash="232d3bc2d1d9510625985ff7c89767598ffea5bc6e5e2882c791313f5a43f723"
fi

task_working_dir
download "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz" "sha256" "$hugo_hash"
extract_download "hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz"

install -D -m 755 "hugo" "$DEV_INSTALL_PREFIX/bin/hugo"

stamp
