#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

hugo_version="0.155.3"
hugo_hash="b98243d840f904367ebfaeb53d3c8e51d89a4edec518ef420c1fb3eae3a9cbb1"
if [ "$TARGETARCH" == "arm64" ]; then
  hugo_hash="3abf1f6cd562f07eb21055b26d5a847ede90068dbfe71a1378fe6f0f6401759c"
fi

task_working_dir
download "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz" "sha256" "$hugo_hash"
extract_download "hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz"

install -D -m 755 "hugo" "$DEV_INSTALL_PREFIX/bin/hugo"

stamp
