#!/usr/bin/env bash

set -e -u -x
source ./tasks/helpers.sh

hugo_version="0.165.0"
hugo_hash="f43494894cdf4a8630a201d5c828051c77f523cc66bb3938b30806835470ac20"
if [ "$TARGETARCH" == "arm64" ]; then
  hugo_hash="f40ebc44dfda3896cecd3ae7ed44f5c44c4b4a30a2b7d976ece6da62da699a58"
fi

task_working_dir
download "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz" "sha256" "$hugo_hash"
extract_download "hugo_extended_${hugo_version}_linux-${TARGETARCH}.tar.gz"

install -D -m 755 "hugo" "$DEV_INSTALL_PREFIX/bin/hugo"

stamp
