#!/usr/bin/env bash


set -e -u -x
source ./tasks/helpers.sh

nodejs_version="22.22.0"
nodejs_hash="9aa8e9d2298ab68c600bd6fb86a6c13bce11a4eca1ba9b39d79fa021755d7c37"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="x64"
elif [ "$TARGETARCH" == "arm64" ]; then
  nodejs_hash="1bf1eb9ee63ffc4e5d324c0b9b62cf4a289f44332dfef9607cea1a0d9596ba6f"
fi

task_working_dir
download "https://nodejs.org/dist/v$nodejs_version/node-v$nodejs_version-linux-${download_arch}.tar.xz" "sha256" "$nodejs_hash"
extract_download "node-v$nodejs_version-linux-${download_arch}.tar.xz"

mkdir -p "$DEV_INSTALL_PREFIX"
rsync -a --itemize-changes "node-v$nodejs_version-linux-${download_arch}/" "$DEV_INSTALL_PREFIX/"

stamp
