#!/usr/bin/env bash


set -e -u -x
source ./tasks/helpers.sh

nodejs_version="22.23.1"
nodejs_hash="9749e988f437343b7fa832c69ded82a312e41a03116d766797ac14f6f9eee578"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="x64"
elif [ "$TARGETARCH" == "arm64" ]; then
  nodejs_hash="0294e8b915ab75f92c7513d2fcb830ae06e10684e6c603e99a87dbf8835389c1"
fi

task_working_dir
download "https://nodejs.org/dist/v$nodejs_version/node-v$nodejs_version-linux-${download_arch}.tar.xz" "sha256" "$nodejs_hash"
extract_download "node-v$nodejs_version-linux-${download_arch}.tar.xz"

mkdir -p "$DEV_INSTALL_PREFIX"
rsync -a --itemize-changes "node-v$nodejs_version-linux-${download_arch}/" "$DEV_INSTALL_PREFIX/"

stamp
