#!/usr/bin/env bash


set -e -u -x
source ./tasks/helpers.sh

nodejs_version="22.23.2"
nodejs_hash="d60acfe00a2932254bb0ad20e01b0d74397a0875595de719654b214f4b03f307"

download_arch="$TARGETARCH"
if [ "$TARGETARCH" == "amd64" ]; then
  download_arch="x64"
elif [ "$TARGETARCH" == "arm64" ]; then
  nodejs_hash="fff4078c5def658577f92c88db7db3bc0072924bfb93fe52c1e744a54e94abb8"
fi

task_working_dir
download "https://nodejs.org/dist/v$nodejs_version/node-v$nodejs_version-linux-${download_arch}.tar.xz" "sha256" "$nodejs_hash"
extract_download "node-v$nodejs_version-linux-${download_arch}.tar.xz"

mkdir -p "$DEV_INSTALL_PREFIX"
rsync -a --itemize-changes "node-v$nodejs_version-linux-${download_arch}/" "$DEV_INSTALL_PREFIX/"

stamp
